### ISSUE TITLE
Suggestion: Spoilers in editor

### ISSUE THREAD

**Issue by LintyCarcass22** [logonoff/obsidian-inline-spoilers#1]
This might be a bit janky when editing but would be nice to have as an option.
I have a DnD character sheet in Obsidian and really like that I can now hide information from my friends.
But if I have to edit something my spoilers will be revealed.

Again, just a suggestion. Thanks for the plugin, the other available ones all require multiple lines.

**Comment by logonoff** [comment]
Feature added in 1.1.0 as a beta test
