### ISSUE TITLE
Error trying to update to 1.1.0

### ISSUE THREAD

**Issue by sirlancelot** [logonoff/obsidian-inline-spoilers#2]
Obsidian is trying to update to 1.1.0 but it says there's an error: 
![image](https://github.com/user-attachments/assets/860dfd2c-8156-47f5-83ca-4245aecb7384)

**Comment by logonoff** [comment]
This should be fixed now, does it still ask for you to update to 1.1.0?

**Comment by sirlancelot** [comment]
Looks like that did it. Thanks!
