### ISSUE TITLE
Request: Add automatic applying of spoiler to highlight text via Format dropdown when right clicking

### ISSUE THREAD

**Issue by QuestionQuest117** [logonoff/obsidian-inline-spoilers#5]
Please make it so when you highlight text, right click, and then look in the dropdown menu, there is an option to make the text spoiler. Once selected, it puts double || outside of the selected text, cognizant of any additional formatting such as bold

**Comment by logonoff** [comment]
This may not be possible given the constraints of Obsidian plugins. Please feel free to contribute if you can find a way to hook into the `Editor Menu > Format` context menu, please feel free to reopen/reply to this ticket or make a PR. 

You could add commands to the editor menu using another third-party plugin such as [Obsidian Commander](https://github.com/phibr0/obsidian-commander)
